-- Unified Events Table
-- Stores normalized events from all vendors (DNAC, Mist, Arista SD-WAN, Arista WLC)
-- Optimized for time-series queries with partitioning by day

CREATE DATABASE IF NOT EXISTS naxis;

CREATE TABLE IF NOT EXISTS naxis.events
(
    -- Identity
    event_id String,

    -- Temporal (partitioning key)
    timestamp DateTime64(3),
    received_at DateTime64(3),

    -- Source
    source LowCardinality(String),  -- dnac, mist, arista_sdwan, arista_wlc
    source_event_id String,

    -- Classification
    severity LowCardinality(String),  -- critical, major, minor, warning, info, debug
    category LowCardinality(String),  -- connectivity, performance, security, etc
    event_type LowCardinality(String),  -- link_down, high_cpu, etc

    -- Content
    title String,
    description String,

    -- Device Information
    device_id String,
    device_name String,
    device_ip String,
    device_type LowCardinality(String),  -- switch, router, ap, controller
    site_id String,
    site_name String,

    -- Client Information
    client_id String,
    client_mac String,
    client_ip String,

    -- Interface Information
    interface_name String,

    -- Tags (for filtering)
    tags Array(String),

    -- Correlation
    incident_id String,  -- Linked incident (empty if not correlated)
    correlation_key String,  -- Key used for correlation

    -- Metadata
    metadata String,  -- JSON blob for vendor-specific data
    raw_event String  -- Original vendor event (JSON blob)
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(timestamp)  -- Daily partitions for efficient pruning
ORDER BY (source, severity, timestamp, device_id)  -- Optimized for common queries
TTL timestamp + INTERVAL 90 DAY  -- Retain events for 90 days
SETTINGS index_granularity = 8192;

-- Indexes for fast filtering
ALTER TABLE naxis.events ADD INDEX idx_device_id device_id TYPE bloom_filter GRANULARITY 1;
ALTER TABLE naxis.events ADD INDEX idx_site_id site_id TYPE bloom_filter GRANULARITY 1;
ALTER TABLE naxis.events ADD INDEX idx_incident_id incident_id TYPE bloom_filter GRANULARITY 1;
ALTER TABLE naxis.events ADD INDEX idx_event_type event_type TYPE set(0) GRANULARITY 1;
ALTER TABLE naxis.events ADD INDEX idx_tags tags TYPE bloom_filter GRANULARITY 1;

-- Materialized view for event counts by source and severity
CREATE MATERIALIZED VIEW IF NOT EXISTS naxis.events_summary_by_hour
ENGINE = SummingMergeTree()
PARTITION BY toYYYYMM(hour)
ORDER BY (hour, source, severity)
POPULATE
AS SELECT
    toStartOfHour(timestamp) AS hour,
    source,
    severity,
    category,
    count() AS event_count
FROM naxis.events
GROUP BY hour, source, severity, category;

-- Materialized view for device event counts
CREATE MATERIALIZED VIEW IF NOT EXISTS naxis.events_by_device
ENGINE = SummingMergeTree()
PARTITION BY toYYYYMM(hour)
ORDER BY (hour, device_id, severity)
POPULATE
AS SELECT
    toStartOfHour(timestamp) AS hour,
    device_id,
    device_name,
    site_id,
    severity,
    count() AS event_count
FROM naxis.events
WHERE device_id != ''
GROUP BY hour, device_id, device_name, site_id, severity;

-- Materialized view for site event counts
CREATE MATERIALIZED VIEW IF NOT EXISTS naxis.events_by_site
ENGINE = SummingMergeTree()
PARTITION BY toYYYYMM(hour)
ORDER BY (hour, site_id, severity)
POPULATE
AS SELECT
    toStartOfHour(timestamp) AS hour,
    site_id,
    site_name,
    severity,
    category,
    count() AS event_count
FROM naxis.events
WHERE site_id != ''
GROUP BY hour, site_id, site_name, severity, category;

-- Comments
COMMENT ON TABLE naxis.events IS 'Unified event store for all network telemetry';
COMMENT ON COLUMN naxis.events.event_id IS 'UUID generated by worker';
COMMENT ON COLUMN naxis.events.timestamp IS 'Event occurrence time (vendor-reported)';
COMMENT ON COLUMN naxis.events.received_at IS 'Ingestion time (worker timestamp)';
COMMENT ON COLUMN naxis.events.source IS 'Vendor source: dnac, mist, arista_sdwan, arista_wlc';
COMMENT ON COLUMN naxis.events.severity IS 'Severity: critical, major, minor, warning, info, debug';
COMMENT ON COLUMN naxis.events.incident_id IS 'Linked incident ID (empty if not correlated)';
